$gdxIn C:\Users\oliver\Documents\RUB\01_Projekte\StEAM\Programme\StEAM_model\backbone-master\input/inputData.gdx
$onEmpty
$offEolCom
$eolCom !!
$LOADDCM emission
$LOADDCM flow
$LOADDCM grid
$LOADDCM group
$LOADDCM node
$LOADDCM restype
$LOADDCM unit
$LOADDCM unittype !!empty
$LOADDCM flowUnit
$LOADDCM restypeDirection !!empty
$LOADDCM uGroup
$LOADDCM unitUnittype !!empty
$LOADDCM effLevelGroupUnit
$LOADDCM gnGroup
$LOADDCM unitUnitEffLevel !!empty
$LOADDCM gn2nGroup !!empty
$LOADDCM gnuGroup !!empty
$LOADDCM p_unit
$LOADDCM p_s_discountFactor !!empty
$LOADDCM p_groupPolicy !!empty
$LOADDCM p_gn
$LOADDCM p_gnn
$LOADDCM p_gnu_io
$LOADDCM p_gnuBoundaryProperties !!empty
$LOADDCM p_unitConstraint !!empty
$LOADDCM p_unitConstraintNode
$LOADDCM p_groupReserves !!empty
$LOADDCM p_groupReserves3D !!empty
$LOADDCM p_groupReserves4D !!empty
$LOADDCM p_gnuReserves !!empty
$LOADDCM p_gnnReserves !!empty
$LOADDCM p_gnuRes2Res !!empty
$LOADDCM p_gnBoundaryPropertiesForStates
$LOADDCM p_uStartupFuel !!empty
$LOADDCM p_nEmission
$LOADDCM p_storageValue !!empty
$LOADDCM p_groupPolicyUnit
$LOADDCM ts_unit !!empty
$LOADDCM ts_reserveDemand !!empty
$LOADDCM ts_cf
$LOADDCM ts_price !!empty
$LOADDCM ts_priceChange
$LOADDCM ts_influx
$LOADDCM ts_node !!empty
$LOADDCM ts_gnn !!empty
$LOADDCM ts_storageValue !!empty
$LOADDCM t_invest
$LOADDCM sGroup !!empty
$LOADDCM uss_bound !!empty
$LOADDCM gnss_bound !!empty
$LOADDCM utAvailabilityLimits
$LOADDCM unit_fail !!empty
$LOADDCM restypeReleasedForRealization !!empty
$LOADDCM restype_inertia !!empty
$LOADDCM p_gnuEmission !!empty
$LOADDCM ts_emissionPriceChange !!empty
$LOADDCM p_groupPolicyEmission
$LOADDCM s_config_info
$LOADDCM s_config_alternative
$LOADDCM s_config_value
$LOADDCM s_config_parameter
$LOADDCM s_config_object
$LOADDCM s_countries
$LOADDCM s_regions
$LOADDCM s_scenario
$LOADDCM s_alternative
$LOADDCM steam_subset_countries
$LOADDCM steam_model_config
$LOADDCM steam_scenarioAlternative
$offEmpty
